### PR TITLE
Add D2 support

### PR DESCRIPTION
**Pull request by goto1134**
Adds D2 exporter

https://d2lang.com/

### CODE REVIEW

**Comment by goto1134** [comment]
@klu2 @simonbrowndotje , I would like to add D2 export support to the CLI tools and VS Code extension. 

Could you please, review the PR?

What is the next release date approximately?

**Comment by goto1134** [comment]
I must mention that 
* there is no support for element descriptions since the d2 elements do not have such properties;
* also, the relationship font was not implemented since the default d2 value looks fine, and  the default structurizr is too big.

**Comment by simonbrowndotje** [comment]
Thanks for the PR. Can I suggest that you host this in your own repo, publish it to Maven Central, and I'll include it via a reference from the CLI?

**Comment by goto1134** [comment]
Ok! I added an issue to the CLI repository with reference to the published library https://github.com/structurizr/cli/issues/89.

**Pull request closed without merging**
