### PR TITLE
resolves #11 export theme icons to PlantUML format

### LINKED ISSUE #11: Allow to export sprites to PlantUML
PlantUML allows to pass sprites to diagrams in order to have all kinds of logos in the generated diagrams, see https://github.com/plantuml-stdlib/C4-PlantUML#getting-started

In the code that looks like that:

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

Person(user, "Customer", "People that need products", $sprite="users")
Container(spa, "SPA", "angular", "The main interface that the customer interacts with", $sprite="angular")
Container(api, "API", "java", "Handles all business logic", $sprite="java")
ContainerDb(db, "Database", "Microsoft SQL", "Holds product, order and invoice information", $sprite="msql_server")

Rel(user, spa, "Uses", "https")
Rel(spa, api, "Uses", "https")
Rel_R(api, db, "Reads/Writes")
@enduml
```

which results in such a diagram:

image

It would be great to have that in the `C4PlantUMLExporter`.

Adding separate includes is already possible via `com.structurizr.export.plantuml.AbstractPlantUMLExporter#PLANTUML_INCLUDES_PROPERTY`, what we need to achieve is to add the sprites somehow from the model.

I thought a bit how that could be integrated into the method `com.structurizr.export.plantuml.C4PlantUMLExporter#writeElement` without breaking things. We could of course pass the content of `container.getTechnology()` or `component.getTechnology()` as sprite to the `writer` but that will make the diagram look weird when no sprite can be found for a given technology (besides that I don't know if a technology is always the best indicator for a sprite).

I'd therefore extract the code which finally writes the Container or Component to the writer to a strategy interface which can be exchanged by clients, leaving the default-implementation as-is in the current repo in order to not break existing things.

If you want I can provide a PR how that could look like.

Probably I could catch https://github.com/structurizr/export/issues/2 then as well.

### PR DESCRIPTION
**Pull request by Mogztter**
#### Point to tackle

As you can see below, images are not automatically scaled. The AWS theme provided by Structurizr is using relatively high resolution images: https://structurizr.com/help/theme?url=https://static.structurizr.com/themes/amazon-web-services-2020.04.30/theme.json

PlantUML supports a `scale` attribute, for instance:

```
img:https://static.structurizr.com/themes/amazon-web-services-2020.04.30/AWS-Auto-Scaling_light-bg@4x.png{scale=0.1}
```

The main issue is that we don't know the size of images so we cannot blindly apply a scale. In other words, a 0.1 scale is fine if the image size is 200px x 200px but won't be so great when the image size is 20px x 20px.

Also, I noticed that not all images in the AWS theme have the same size:

Anyway, here's the result using AWS theme:

#### C4 PlantUML

I guess we could also configure border colors?

#### PlantUML

resolves #11

### CODE REVIEW

**Comment by Mogztter** [comment]
@simonbrowndotje Any thoughts on this?

**Comment by simonbrowndotje** [comment]
Without a way to specify an icon size in PlantUML, I'm uncomfortable merging this I'm afraid, because I can foresee issues being continually raised to say that icon support doesn't work as expected ... and I don't really want to deal with that. It's certainly possible to modify the AWS/Azure/GCP/etc themes to use a specific icon size, but many users are using their own icons.

**Comment by Mogztter** [comment]
> Without a way to specify an icon size in PlantUML

That's probably the best way to resolve this issue.

> I'm uncomfortable merging this I'm afraid, because I can foresee issues being continually raised to say that icon support doesn't work as expected ... and I don't really want to deal with that. It's certainly possible to modify the AWS/Azure/GCP/etc themes to use a specific icon size, but many users are using their own icons.

One way, would be to automatically get image dimensions (for instance using https://stackoverflow.com/a/1560052) and apply the corresponding scale. What do you think?

**Comment by simonbrowndotje** [comment]
I've added icon support to the `StructurizrPlantUMLExporter` and, as you suggested, the icons are loaded so that the appropriate scale can be determined. A diagram key/legend is now also created. This is available in v1.7.0 on Maven Central. Here's [the AWS example](https://structurizr.com/dsl?example=amazon-web-services&renderer=plantuml).

image

image

**Comment by Mogztter** [comment]
That's awesome 😍

**Comment by Mogztter** [comment]
I guess we can close this pull request?

**Pull request closed without merging**
